### ISSUE TITLE
what is measurement characteristic?

### ISSUE THREAD

**Issue by lukaskris** [aashari/mi-band-2#1]
what function measurementCharacteristic and controlCharacteristic??

**Comment by aashari** [comment]
it is a Bluetooth characteristic of device, if you want to see the value of the characteristic you can open this file: https://github.com/aashari/mi-band-2/blob/master/app/src/main/java/id/aashari/code/miband2/Helpers/CustomBluetoothProfile.java

**Comment by lukaskris** [comment]
ok.. thankyou bro, ud jalan d miband 2 nya, tapi kalo mau tau HRMnya sdh selesai melakukan measurement gimana? kebetulan sama2 indo

**Comment by aashari** [comment]
Kalau nggak salah dikodingan saya di MainActivity sudah ada contoh untuk HRM, coba dicek disana setelah dia melakukan Measurement dia bakal tampilin, kalau nggak salah waktu itu saya tampilinnya di loggernya.

**Comment by bonabrian** [comment]
gimana buat untuk connect melalui aplikasi nya bro?
keren lah, yang selama dicari ketemu juga, nice work bro

**Comment by aashari** [comment]
Ada di fungsi startConnecting bro
