### ISSUE TITLE
Connect and pair

### ISSUE THREAD

**Issue by abelduran1** [aashari/mi-band-2#4]
Hi, your project is awsome but if I close the Mifit app yout app not function. ¿How can I connect and pair with Mi Band 2 programamtically? Without use the Mifit officical app. Thanks in advance.

**Comment by cuiti** [comment]
I've been working on this for a few days now, for listening to the heart rate monitor in my app. Xiaomi has made it really difficult to use this wearable from third party apps. Even if you manage to detect the Bluetooth device, when you try to listen to a characteristic, it returns a GATT_WRITE_NOT_PERMIT 0x03 error. 
The only way to make it work is that the client device is paired, has the official app installed, and has the "discoverable" option enabled.

**Comment by abelduran1** [comment]
Thanks for your response, but I think that is posible to connect without the official app installed, because this third party app do that: https://github.com/Freeyourgadget/Gadgetbridge

The next websites are very interesting: 
- https://leojrfs.github.io/writing/miband2-part1-auth/
- https://stackoverflow.com/questions/41417747/connection-to-mi-band-2?answertab=votes#tab-top

**Comment by gokulrajkc** [comment]
Hi , 
Thanks for your code, the app gets connected to the device and it gets connected also.

While getting the heart rate i am getting the error

java.lang.NullPointerException: Attempt to invoke virtual method 'android.bluetooth.BluetoothGattCharacteristic android.bluetooth.BluetoothGattService.getCharacteristic(java.util.UUID)' on a null object reference
                                                                             at id.aashari.code.miband2.Activities.MainActivity.startScanHeartRate(MainActivity.java:149)
                                                                             at id.aashari.code.miband2.Activities.MainActivity$5.onClick(MainActivity.java:119)

**Comment by Miha-x64** [comment]
The SO answer really works (using Mi Band 3). But such auth process takes much time and requires clicking the button on a band.
Does anyone know how does it work in GadgetBridge? It requires clicking on a button only for the first time, subsequent connections happen automatically.

**Comment by aashari** [comment]
Hi all, thanks for creating the issue and replying the issue, but unfortunately I'm not maintaining this repository anymore, so sorry about this, I hope you find the answer by yourself
