### ISSUE TITLE
Fetching Heart Rate - ISSUE

### ISSUE THREAD

**Issue by gokulrajkc** [aashari/mi-band-2#5]
Hi,
 The code is useful, it lists the Bluetooth devices and gets connected .

  I am getting error when fetching heart rate 

![heartrateissue](https://user-images.githubusercontent.com/11208646/38557131-a550a5b8-3ce9-11e8-8894-b2070a6c4ed3.png)

**Comment by aashari** [comment]
Hi @gokulrajkc, thanks, but I'm so sorry I'm not maintaining this repo anymore, I hope you find the solution yourself
