### ISSUE TITLE
Heart Rate Button to Device Scanner?

### ISSUE THREAD

**Issue by napat1996** [aashari/mi-band-2#6]
I cloned your project and try to run on my phone. After I touch "heart rate" button, my device switched to "device scan" activity and not show any heart rate data. The only thing shown on my phone was device name.

I am new to Android development. Please help me. 😭

**Comment by Jh3xX** [comment]
I have the same problem  startScanHeartRate() doesnt work help please!

**Comment by aashari** [comment]
Hi @napat1996 and @JhosepNoel, I'm really sorry I don't maintain the repo anymore, also so sorry for late respond, I hope you already find the solution by yourself
